[package]
name = "gameboy_emulator"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os="macos")'.dependencies.sdl2]
features=["bundled"]
version="0.36.0"

[dependencies]
log = "0.4.26"
thiserror = "2.0.12"
